[package]
name = "seed-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"