[package]
name = "seed-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.10.0"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7.12"